name: Docker Build and Push

on:
  push:
    branches: ["flexai-main"]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: rg.fr-par.scw.cloud/rag-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_REGISTRY_PAAS_PROJECT_RW_SECRET }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/flexai-main' }}
          tags:  ${{ env.REGISTRY }}/rag-app:${{ github.sha }}